# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5402e4dec37c6913dec5cec180a24164806753846e764fde4f2d54a32101f852da2e080466592902ac40ac9d44a1ed80d2c4296984dd584854a030a6c6bd725d

test:
  secret_key_base: 6fd3e26db8bad5fc20aa5f203685d0d18d116d593d7f7b2823ff3cab7ac7712d4cb70c2515dde35c46364c0f00b0c6014766b2a6e317f2ed6e86fe75f2e49278

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
